apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rust
  namespace: clima-app
  labels: { app: api-rust }
spec:
  replicas: 1
  selector: { matchLabels: { app: api-rust } }
  template:
    metadata: { labels: { app: api-rust } }
    spec:
      containers:
      - name: api-rust
        image: nonalcoholic-dixie-freshly.ngrok-free.dev/api-rust:v1           # <-- cambia esto
        imagePullPolicy: Always
        env:
        - name: GRPC_SERVER_URL          # Rust → client-go proxy gRPC
          value: "http://client-go-service:50052"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet: { path: /, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: api-rust-service
  namespace: clima-app
  labels: { app: api-rust }
spec:
  # Para pruebas rápidas lo exponemos; si prefieres Ingress, cambia a ClusterIP y crea el Ingress
  type: LoadBalancer
  selector: { app: api-rust }
  ports:
  - name: http
    port: 80
    targetPort: 8080
