apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-rust-ingress
  namespace: clima-app
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: "136.117.88.73"  # Aquí va la IP pública de tu servicio
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-rust-service
            port:
              number: 80
