# rabbit-consumer.yaml (opcional, si tambi√©n lo despliegas)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-consumer
  namespace: clima-app
  labels:
    app: rabbit-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
      - name: rabbit-consumer
        image: nonalcoholic-dixie-freshly.ngrok-free.dev/rabbit-consumer:v1
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        - name: RABBIT_QUEUE
          value: "clima"
        - name: VALKEY_SERVICE_URL
          value: "valkey:6379"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
