apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-go
  namespace: clima-app
  labels: { app: server-go }
spec:
  replicas: 1
  selector: { matchLabels: { app: server-go } }
  template:
    metadata: { labels: { app: server-go } }
    spec:
      containers:
      - name: server-go
        image: nonalcoholic-dixie-freshly.ngrok-free.dev/server-go:v1          # <-- cambia esto
        imagePullPolicy: Always
        ports:
        - name: grpc
          containerPort: 50051
        env:
        - name: WRITER_TARGET            # both | kafka | rabbit | random
          value: "both"
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: KAFKA_TOPIC
          value: "clima"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq-service:5672/"
        readinessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          tcpSocket: { port: 50051 }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: server-go-service
  namespace: clima-app
  labels: { app: server-go }
spec:
  type: ClusterIP
  selector: { app: server-go }
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
